
export const SET_ADMIN_PRODUCTS = "SET_ADMIN_PRODUCTS";

export const SET_PRICE = "SET_PRICE";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
export const SET_MIN = "SET_MIN";

export const REMOVE_PRODUCT_MY = "REMOVE_PRODUCT_MY";
 
export const ACTIVE_SINGLE_PRODUCT = "ACTIVE_SINGLE_PRODUCT";

export const SET_ACTIVE_PRODUCTS = "SET_ACTIVE_PRODUCTS";
export const CLEAR_ALERT_STATE = "CLEAR_ALERT_STATE";


export const SET_MATERIALGOINGTOFINISH = "SET_MATERIALGOINGTOFINISH"

export const DE_ACTIVE_SINGLE_PRODUCT = "DE_ACTIVE_SINGLE_PRODUCT";


export const SET_PRODUCT_GOINGTOFINISH = "SET_PRODUCT_GOINGTOFINISH";


export const SET_QUANTITY = "SET_QUANTITY";
