

export const SET_PRODUCTS_CART = "SET_PRODUCTS_CART";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


export const CHANGE_AMOUNT = "CHANGE_AMOUNT";

export const DELETE_ALL = "DELETE_ALL";
