export const SET_ADMIN_MATERIALS = "SET_ADMIN_MATERIALS";
export const SET_SINGLE_MATERIAL = "SET_SINGLE_MATERIAL";
export const SET_MINIMUM_MATERIAL = "SET_MINIMUM_MATERIAL";
export const REMOVE_MATERIAL_MY = "REMOVE_MATERIAL_MY";

export const CLEAR_MATERIALS_STATE = 'CLEAR_MATERIALS_STATE'
export const SET_QUANTITY = 'SET_QUANTITY'

