

export const SET_ORDER_PLACE = "SET_ORDER_PLACE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SET_NON_ACTIVE_ORDER_PLACE = "SET_NON_ACTIVE_ORDER_PLACE";
export const SET_UPDATE_PRODUCT = 'SET_UPDATE_PRODUCT'
export const CLEARUPDATE = "CLEARUPDATE"
export const ACTIVE_ORDERS = "ACTIVE_ORDERS"
export const CLOSE_POP_UP = "CLOSE_POP_UP"
export const SET_ORDERS_INFO = "SET_ORDERS_INFO"
export const REMOVE_ORDER_NOW = "REMOVE_ORDER_NOW"
export const ACCETP_ORDER = "ACCETP_ORDER"
export const SET_USERS_NOT_ACTIVE_ORDERS = "SET_USERS_NOT_ACTIVE_ORDERS"
