export const ADD_PROVIDER = "ADD_PROVIDER";

export const REMOVE_PROVIDE = "REMOVE_PROVIDE";

export const SET_ALL_PROVIDERS = "SET_ALL_PROVIDERS";

export const SET_SINGLE_PROVIDER = "SET_SINGLE_PROVIDER";

export const EDIT_PROVIDER = "EDIT_PROVIDER";



