

export const SET_USER_ORDERS = "SET_USER_ORDERS";

export const REMOVE_USERS_ORDER = "REMOVE_USERS_ORDER";

export const SET_USER_ORDER_INFO_PAGE = "SET_USER_ORDER_INFO_PAGE";

export const SET_USER_NOT_ACTIVE_ORDERS = "SET_USER_NOT_ACTIVE_ORDERS";


export const REMOVE_USER_NOT_ACTIVE_ORDERS = "REMOVE_USER_NOT_ACTIVE_ORDERS";
